### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by oak-tree** [hellock/icrawler#13]
Hey, I tried to run the `Google example` but got the following error

`Traceback (most recent call last):
  File "google.py", line 1, in <module>
    from icrawler.builtin import BaiduImageCrawler, BingImageCrawler, GoogleImageCrawler
  File "/home/oak/venv2/local/lib/python2.7/site-packages/icrawler/__init__.py", line 4, in <module>
    from .crawler import Crawler
  File "/home/oak/venv2/local/lib/python2.7/site-packages/icrawler/crawler.py", line 10, in <module>
    from icrawler import storage as storage_package
  File "/home/oak/venv2/local/lib/python2.7/site-packages/icrawler/storage/__init__.py", line 1, in <module>
    from .base import BaseStorage
  File "/home/oak/venv2/local/lib/python2.7/site-packages/icrawler/storage/base.py", line 4
    class BaseStorage(metaclass=ABCMeta):
                               ^
SyntaxError: invalid syntax
`

**Comment by hellock** [comment]
Thanks for pointing out this, the latest codes are compatible with Python 2.7 now.
