### ISSUE TITLE
Baidu invalid escape | JSON

### ISSUE THREAD

**Issue by BlkChockr** [hellock/icrawler#16]
Hey again,

I'm currently trying to download from Google, Bing and Baidu.

Google and Bing work perfectly, but Baidu gives me this error:

```python
Exception in thread parser-001:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/icrawler/parser.py", line 105, in worker_exec
    for task in self.parse(response, **kwargs):
  File "/usr/lib/python3.6/site-packages/icrawler/builtin/baidu.py", line 32, in parse
    content = json.loads(response.content.decode('utf-8'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 8 column 113 (char 10372)
```
Also, for another part of the JSON:

```python
json.decoder.JSONDecodeError: Invalid \escape: line 20 column 110 (char 19232)
```

Could you give me a hint what seems to be the problem? Or is it really Baidu providing invalid json?

Search query was still `Duck`.

Thank you!

**Comment by hellock** [comment]
Hey it seems that the returned json string is broken, I tried putting the returned json string in an online parser and it fails. If you use other searching keywords like "bird" it will be ok.

**Comment by BlkChockr** [comment]
Oh, okay! Thank you :)

**Comment by peterprokop** [comment]
Hey, got the same problem. I think `icrawler` could handle this better - inform that Baidu sometimes returns incorrect data and don't hang the entire script after that.

**Comment by hellock** [comment]
@peterprokop thanks for your information. Exception handling is added for such problem now.
