### ISSUE TITLE
Exception in parser causes program freeze

### ISSUE THREAD

**Issue by Ettard** [hellock/icrawler#22]
When I crawl pictures with 4 parsers, I see exception: 

Exception in thread parser-001:
Traceback (most recent call last):
  File "/home/q/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/q/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/q/anaconda2/lib/python2.7/site-packages/icrawler/parser.py", line 104, in worker_exec
    for task in self.parse(response, **kwargs):
  File "/home/q/anaconda2/lib/python2.7/site-packages/icrawler/builtin/bing.py", line 21, in parse
    img_url = '{}.jpg'.format(match.group(1))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 48-56: ordinal not in range(128)
...
2017-05-05 16:36:35,446 - INFO - downloader - no more download task for thread downloader-001
2017-05-05 16:36:35,447 - INFO - downloader - thread downloader-001 exit
2017-05-05 16:36:35,634 - INFO - downloader - no more download task for thread downloader-003
2017-05-05 16:36:35,635 - INFO - downloader - thread downloader-003 exit
2017-05-05 16:36:41,574 - INFO - downloader - no more download task for thread downloader-004
2017-05-05 16:36:41,574 - INFO - downloader - thread downloader-004 exit
2017-05-05 16:36:56,608 - INFO - downloader - no more download task for thread downloader-002
2017-05-05 16:36:56,608 - INFO - downloader - thread downloader-002 exit

Then the program froze.
I changed <a href=https://github.com/hellock/icrawler/blob/master/icrawler/crawler.py>crawler.py</a>,line 183 to:
      print threading.active_count();time.sleep(1)
It shows 2.

**Comment by hellock** [comment]
I need more information to reproduce the error. Could you show me the core codes (including the searching keyword and other params)?

**Comment by Ettard** [comment]
#coding:utf-8
import sys
from icrawler.builtin import BingImageCrawler
def crawl(keyword):
    bing_crawler = BingImageCrawler(parser_threads=4, downloader_threads=4,
                   storage={'root_dir': keyword+"_bing"})
    bing_crawler.crawl(keyword=keyword, offset=0, max_num=1000,
                   min_size=None, max_size=None)

if __name__ == "__main__":
    crawl("香蕉")

**Comment by hellock** [comment]
Thanks for pointing this out. The bug is caused by the encoding issue of python 2 and it is fixed in the latest version.

**Comment by Ettard** [comment]
Now it's ok. Thanks.
